- name: Update repositories (Debian/Ubuntu)
  when: ansible_facts.os_family == "Debian"
  block:
  - name: Kubernetes - Download GPG keyring
    delay: 5
    register: kubernetes_download_gpg_keyring
    retries: 2
    timeout: 300
    until: kubernetes_download_gpg_keyring is succeeded
    ansible.builtin.get_url:
      dest: /etc/apt/keyrings/kubernetes-{{ kubernetes_version }}
      group: root
      mode: '0644'
      owner: root
      url: "{{ kubernetes_mirror_gpgkey }}"

  - name: Add an apt signing key for Kubernetes
    changed_when: false
    ansible.builtin.command:
      cmd: gpg --batch --yes --dearmor /etc/apt/keyrings/kubernetes-{{ kubernetes_version }}
      creates: /etc/apt/keyrings/kubernetes-{{ kubernetes_version }}.gpg

  - name: Set file permissions for keyring
    ansible.builtin.file:
      group: root
      mode: '0644'
      owner: root
      path: /etc/apt/keyrings/kubernetes-{{ kubernetes_version }}.gpg
      state: file

  - name: Remove old style Kubernetes apt repository
    ansible.builtin.file:
      path: /etc/apt/sources.list.d/kubernetes.list
      state: absent

  - name: Get a list of Kubernetes-*.list apt repository files
    register: kubernetes_list_files
    ansible.builtin.find:
      paths: /etc/apt/sources.list.d/
      patterns: kubernetes-*.list

  - name: Remove old Kubernetes apt list repository files
    loop: "{{ kubernetes_list_files.files }}"
    ansible.builtin.file:
      path: "{{ item.path }}"
      state: absent

  - name: Get a list of Kubernetes-*.sources apt repository files
    register: kubernetes_sources_files
    ansible.builtin.find:
      paths: /etc/apt/sources.list.d/
      patterns: Kubernetes-*.sources

  - name: Remove old Kubernetes apt sources repository files
    loop: "{{ kubernetes_sources_files.files }}"
    ansible.builtin.file:
      path: "{{ item.path }}"
      state: absent

  - name: Add apt repository
    ansible.builtin.deb822_repository:
      install_python_debian: true
      name: Kubernetes-{{ kubernetes_version }}
      signed_by: /etc/apt/keyrings/kubernetes-{{ kubernetes_version }}.gpg
      suites: ["/"]
      uris: ["{{ kubernetes_mirror }}"]

  - name: Remove old Docker apt repository file
    ansible.builtin.file:
      path: /etc/apt/sources.list.d/docker.list
      state: absent

  - name: Add Docker apt repository
    ansible.builtin.deb822_repository:
      components: ["stable"]
      install_python_debian: true
      name: Docker
      signed_by: /etc/apt/keyrings/docker.gpg
      suites: ["{{ ansible_facts[\"distribution_release\"] | lower }}"]
      uris: ["{{ kubernetes_containerd_mirror }}"]

  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: true

  - name: Find latest kubernetes version in apt
    delay: 5
    register: kubernetes_find_latest_version
    retries: 2
    timeout: 300
    until: kubernetes_find_latest_version is succeeded
    ansible.builtin.apt:
      allow_change_held_packages: true
      update_cache: true

- name: Update repositories (RedHat/Rocky/Alma/Fedora)
  when: ansible_facts.os_family == "RedHat"
  block:
  - name: Update Kubernetes repository
    delay: 5
    register: update_kubernetes_repo
    retries: 2
    timeout: 300
    until: update_kubernetes_repo is succeeded
    ansible.builtin.yum_repository:
      baseurl: "{{ kubernetes_mirror }}/"
      description: Kubernetes
      enabled: true
      gpgcheck: true
      gpgkey: "{{ kubernetes_mirror_gpgkey }}"
      name: kubernetes
