- any_errors_fatal: true
  become: true
  hosts: proxies
  name: Configure the proxies
  vars:
    skip_checks: true
  roles:
  - role: kubernetes-defaults
  - role: kubernetes-proxy

- any_errors_fatal: true
  become: true
  gather_facts: true
  hosts:
  - kubernetes
  name: "Install containerd.io"
  serial: 100
  vars:
    containerd_credentials: "{{ kubernetes_containerd_credentials }}"
    containerd_mirror: "{{ kubernetes_containerd_mirror }}"
  roles:
  - role: kubernetes-defaults
  - role: containerd

- any_errors_fatal: true
  become: true
  hosts:
  - kubernetes
  name: Install kubernetes pre-requisites
  serial: 100
  roles:
  - role: kubernetes-defaults
  - role: kubernetes

- any_errors_fatal: true
  become: true
  hosts: control_planes
  name: Pre control plane hooks
  roles:
  - role: kubernetes-defaults
  - role: pre-kubernetes-control-plane

- any_errors_fatal: true
  become: true
  hosts: control_planes
  name: Install Control Planes
  serial: 1
  roles:
  - role: kubernetes-defaults
  - role: kubernetes-control-plane

- any_errors_fatal: true
  become: true
  hosts: control_planes
  name: Post control plane hooks
  roles:
  - role: kubernetes-defaults
  - role: post-kubernetes-control-plane

- any_errors_fatal: true
  become: true
  hosts: worker_nodes
  name: Install worker nodes
  roles:
  - role: kubernetes-defaults
  - role: kubernetes-worker

- any_errors_fatal: true
  become: true
  hosts: worker_nodes
  name: Post worker node hooks
  roles:
  - role: kubernetes-defaults
  - role: post-kubernetes-worker
