- name: Configure the proxies
  any_errors_fatal: true
  become: true
  hosts: proxies
  vars:
    skip_checks: true
  roles:
  - role: kubernetes-defaults
  - role: kubernetes-proxy

- name: "Install containerd.io"
  any_errors_fatal: true
  become: true
  gather_facts: true
  hosts:
  - kubernetes
  serial: 100
  vars:
    containerd_credentials: "{{ kubernetes_containerd_credentials }}"
    containerd_mirror: "{{ kubernetes_containerd_mirror }}"
  roles:
  - role: kubernetes-defaults
  - role: containerd

- name: Install kubernetes pre-requisites
  any_errors_fatal: true
  become: true
  hosts:
  - kubernetes
  serial: 100
  roles:
  - role: kubernetes-defaults
  - role: kubernetes

- name: Pre control plane hooks
  any_errors_fatal: true
  become: true
  hosts: control_planes
  roles:
  - role: kubernetes-defaults
  - role: pre-kubernetes-control-plane

- name: Install Control Planes
  any_errors_fatal: true
  become: true
  hosts: control_planes
  serial: 1
  roles:
  - role: kubernetes-defaults
  - role: kubernetes-control-plane

- name: Post control plane hooks
  any_errors_fatal: true
  become: true
  hosts: control_planes
  roles:
  - role: kubernetes-defaults
  - role: post-kubernetes-control-plane

- name: Install worker nodes
  any_errors_fatal: true
  become: true
  hosts: worker_nodes
  roles:
  - role: kubernetes-defaults
  - role: kubernetes-worker

- name: Post worker node hooks
  any_errors_fatal: true
  become: true
  hosts: worker_nodes
  roles:
  - role: kubernetes-defaults
  - role: post-kubernetes-worker
