- name: Cleanup
  become: true
  hosts: kubernetes
  serial: 100
  tasks:

  - name: Reset kubeadm
    failed_when: false
    notify: reboot
    ansible.builtin.command:
      cmd: kubeadm reset -f
      removes: /etc/kubernetes/kubelet.conf

  - name: Stop systemd units
    failed_when: false
    loop:
    - k8s-certs-renew.timer
    - kubelet.service
    - keepalived.service
    loop_control:
      loop_var: unit
    notify: reboot
    ansible.builtin.systemd_service:
      enabled: false
      name: "{{ unit }}"
      state: stopped

  - name: List containerd containers
    changed_when: false
    failed_when: false
    register: containerd_containers
    ansible.builtin.command:
      cmd: ctr --namespace k8s.io containers ls -q

  - name: Remove containerd containers
    failed_when: false
    loop: "{{ containerd_containers.stdout_lines }}"
    loop_control:
      label: "{{ containerd_image }}"
      loop_var: containerd_image
    notify: reboot
    when: containerd_containers.stdout_lines | length > 0
    ansible.builtin.command:
      cmd: ctr --namespace k8s.io containers rm "{{ containerd_image }}"

  - name: Stop containerd
    failed_when: false
    loop:
    - containerd.service
    loop_control:
      loop_var: unit
    notify: reboot
    ansible.builtin.systemd_service:
      enabled: false
      name: "{{ unit }}"
      state: stopped

  - name: Uninstall packages
    notify: reboot
    ansible.builtin.apt:
      allow_change_held_packages: true
      name:
      - conntrack
      - containerd
      - containerd.io
      - cri-tools
      - keepalived
      - kubeadm
      - kubectl
      - kubelet
      - kubernetes-cni
      state: absent

  - name: Clean up unused packages
    notify: reboot
    ansible.builtin.apt:
      autoremove: true
      purge: true

  # This removes config files left behind by package removal and also removes
  # them from the dpkg database. This prevents issues on future installs where
  # the config files would not be installed because the dpkg database says
  # they are already present.
  - name: Find packages with residual config files
    changed_when: false
    register: residual_packages
    ansible.builtin.command:
      cmd: dpkg-query --show --showformat='${binary:Package} ${db:Status-Abbrev}\n'

  - name: Clean up unused package configuration files
    when: residual_packages.stdout_lines | select('search', ' rc $') | list | length > 0
    ansible.builtin.apt:
      name: "{{ residual_packages.stdout_lines | select('search', ' rc $') | map('split', ' ') | map('first') | list }}"
      purge: true
      state: absent

  - name: Remove files and directories that require rebooting
    failed_when: false
    loop:
    - /etc/sysctl.d/99-kubernetes-cri.conf
    - /etc/sysctl.d/99-non-local-bind.conf
    - /etc/systemd/system/k8s-certs-renew.service
    - /etc/systemd/system/k8s-certs-renew.timer
    loop_control:
      loop_var: file
    notify: reboot
    ansible.builtin.file:
      path: "{{ file }}"
      state: absent

  - name: Daemon reload
    notify: reboot
    ansible.builtin.systemd_service:
      daemon_reload: true

  # Flush handlers to ensure any pending reboots are executed before continuing with cleanup
  - name: Flush handlers
    ansible.builtin.meta: flush_handlers

  - name: Remove files and directories
    failed_when: false
    loop:
    - /etc/apt/keyrings/docker
    - /etc/apt/keyrings/docker.gpg
    - /etc/apt/sources.list.d/docker.list
    - /etc/apt/sources.list.d/kubernetes.list
    - /etc/cni
    - /etc/containerd
    - /etc/default/kubelet
    - /etc/keepalived
    - /etc/kubernetes
    - /opt/cni
    - /opt/containerd
    - /opt/kubernetes
    - /root/.kube
    - /usr/bin/helm
    - /usr/bin/kustomize
    - /var/lib/containerd
    - /var/lib/etcd
    - /var/log/apiserver
    - /var/log/containers
    - /var/log/pods
    - /var/run/containerd
    loop_control:
      loop_var: file
    ansible.builtin.file:
      path: "{{ file }}"
      state: absent

  - name: Find versioned files
    register: kubernetes_files
    ansible.builtin.find:
      paths:
      - /etc/apt/keyrings
      - /etc/apt/sources.list.d
      patterns:
      - kubernetes*

  - name: Remove versioned files
    loop: "{{ kubernetes_files.files }}"
    loop_control:
      label: "{{ file.path }}"
      loop_var: file
    ansible.builtin.file:
      path: "{{ file.path }}"
      state: absent

  - name: Delete users
    loop:
    - etcd
    loop_control:
      loop_var: user
    ansible.builtin.user:
      name: "{{ user }}"
      state: absent

  - name: Delete groups
    loop:
    - etcd
    loop_control:
      loop_var: group
    ansible.builtin.group:
      name: "{{ group }}"
      state: absent

  handlers:

  - name: Reboot
    listen: reboot
    ansible.builtin.reboot:
      connect_timeout: 10
      msg: Reboot host to complete Kubernetes reset
      reboot_timeout: 300
