- name: Pre proxy configuration hooks
  ansible.builtin.include_tasks: "{{ item }}"
  with_items: "{{ kubernetes_hookfiles.pre_proxies }}"
  when: kubernetes_hookfiles.pre_proxies is defined

- name: Validate Proxy Configuration
  ansible.builtin.assert:
    that:
    - vrrp_interface != None
    - vrrp_password != None
    - vrrp_virtual_router_id != None

- name: Copy haproxy.cfg
  ansible.builtin.template:
    src: "{{ kubernetes_proxy_haproxy_config_file }}"
    dest: /etc/kubernetes/config/haproxy.cfg
    owner: root
    group: root
    mode: '0644'

- name: Copy kube-apiserver-proxy manifest
  ansible.builtin.template:
    src: api-server-proxy.yaml.j2
    dest: /etc/kubernetes/manifests/kube-apiserver-proxy.yaml
    owner: root
    group: root
    mode: '0644'

- name: Install keepalived
  ansible.builtin.package:
    name:
    - keepalived
    state: present

- name: Copy keepalived.conf
  ansible.builtin.template:
    src: "{{ kubernetes_proxy_keepalived_config_file }}"
    dest: /etc/keepalived/keepalived.conf
    owner: root
    mode: '0644'

- name: Enable keepalived
  ansible.builtin.systemd_service:
    enabled: true
    name: keepalived

- name: Restart keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    state: restarted
    daemon_reload: true

- name: Set the net.ipv4.ip_nonlocal_bind=1 sysctl
  ansible.builtin.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    sysctl_file: /etc/sysctl.d/99-non-local-bind.conf
    value: '1'
    state: present
    reload: yes

- name: Post proxy configuration hooks
  ansible.builtin.include_tasks: "{{ item }}"
  with_items: "{{ kubernetes_hookfiles.post_proxies }}"
  when: kubernetes_hookfiles.post_proxies is defined
