- name: Pre configure control plane hooks
  loop: "{{ kubernetes_hookfiles.pre_configure_control_planes }}"
  loop_control:
    loop_var: hook
  when:
  - kubernetes_hookfiles.pre_configure_control_planes is defined
  ansible.builtin.include_tasks:
    file: "{{ hook }}"

- name: Configure control plane files
  ansible.builtin.include_tasks:
    file: configure-control-plane.yml

- name: Create etcd group
  ansible.builtin.group:
    gid: 500
    name: etcd
    system: true

- name: Create etcd user
  ansible.builtin.user:
    comment: "etcd user"
    create_home: false
    group: etcd
    name: etcd
    shell: /bin/false
    system: true
    uid: 500

- name: Renew K8S control plane certificates monthly systemd timer
  when: kubernetes_manage_cert_renewal
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    name: k8s-certs-renew.timer
    state: started

- name: Post configure control plane hooks
  loop: "{{ kubernetes_hookfiles.post_configure_control_planes }}"
  loop_control:
    loop_var: hook
  when:
  - kubernetes_hookfiles.post_configure_control_planes is defined
  ansible.builtin.include_tasks:
    file: "{{ hook }}"

- name: Initialize control plane
  delegate_to: "{{ first_kube_control_plane }}"
  run_once: true
  when:
  - kubernetes_initialize_ran is not defined or
    not kubernetes_initialize_ran
  ansible.builtin.import_tasks:
    file: initialize-control-plane.yml

- name: Set kubernetes_initialize_ran to true
  delegate_facts: true
  delegate_to: "{{ node }}"
  loop: "{{ ansible_play_hosts }}"
  loop_control:
    loop_var: node
  run_once: true
  ansible.builtin.set_fact:
    kubernetes_initialize_ran: true

- name: Get CA certificate hash
  changed_when: false
  delegate_to: "{{ first_kube_control_plane }}"
  register: cluster_ca_cert_hash_temp
  run_once: true
  ansible.builtin.shell:
    cmd: |
      set -eo pipefail
      openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | \
      openssl rsa -pubin -outform der 2>/dev/null | \
      openssl dgst -sha256 -hex | sed 's/^.* //'
    executable: /usr/bin/bash

- name: Upload certificates so they are fresh and not expired
  changed_when: true
  delay: 5
  delegate_to: "{{ first_kube_control_plane }}"
  register: kubeadm_upload_cert
  retries: 5
  run_once: true
  until: kubeadm_upload_cert.rc == 0
  ansible.builtin.command:
    cmd: >-
      kubeadm init phase
      --config {{ kubernetes_config_directory }}/kubeadm.yaml
      upload-certs --upload-certs

- name: Set facts
  run_once: true
  ansible.builtin.set_fact:
    cluster_ca_cert_hash: "sha256:{{ cluster_ca_cert_hash_temp.stdout }}"
    kubeadm_upload_token: "{{ kubeadm_upload_cert.stdout_lines[-1] | trim }}"

- name: Join additional control planes to the cluster
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: inventory_hostname in groups['control_planes']
  block:

  - name: Generate join token
    changed_when: true
    delay: 5
    delegate_to: "{{ first_kube_control_plane }}"
    register: temp_token
    retries: 5
    until: temp_token.rc == 0
    ansible.builtin.command:
      cmd: kubeadm token create --ttl 30m

  - name: Set facts
    ansible.builtin.set_fact:
      join_token: "{{ temp_token.stdout }}"

  - name: Configure additional control planes
    when:
    - first_kube_control_plane != inventory_hostname
    - inventory_hostname in groups['control_planes']
    ansible.builtin.import_tasks:
      file: secondary-control-plane.yml

  rescue:

  - name: Fail control plane join
    ansible.builtin.fail:
      msg: >-
        Joining control plane {{ inventory_hostname }} to the cluster failed.

  always:

  - name: Expire join token
    changed_when: true
    delegate_to: "{{ first_kube_control_plane }}"
    when: join_token is defined
    ansible.builtin.command:
      cmd: kubeadm token delete "{{ join_token }}"

- name: Approve CSRs
  ansible.builtin.include_tasks:
    file: approve-csr.yaml
