- name: Install Cilium
  run_once: true
  delegate_to: "{{ first_kube_control_plane }}"
  block:
  - name: Check for Cilium
    register: cilium_installed_cmd
    run_once: true
    ansible.builtin.shell:
      cmd: |
        kubectl get pods -n kube-system --kubeconfig /etc/kubernetes/admin.conf 2> /dev/null | grep cilium > /dev/null 2> /dev/null || echo "Not installed"
        echo "Installed"

  - name: Set install_cilium fact
    run_once: true
    ansible.builtin.set_fact:
      install_cilium: "{{ cilium_installed_cmd.stdout_lines[0] == 'Not installed' }}"

  - name: Copy Cilium values file
    when: install_cilium
    ansible.builtin.template:
      src: cilium.yaml.j2
      dest: "{{ kubernetes_config_directory }}/cilium.yaml"

  - name: Install Cilium Helm repo
    when: install_cilium
    ansible.builtin.shell:
      cmd: |
        set -e
        set -o pipefail
        helm repo add cilium https://helm.cilium.io/
        helm repo update cilium
      executable: /bin/bash

  - name: Install Cilium Helm chart
    register: cilium
    when: install_cilium
    ansible.builtin.shell:
      cmd: |
        set -e
        set -o pipefail
        helm upgrade --install cilium cilium/cilium \
          {{ "--version " + kubernetes_cilium_version if kubernetes_cilium_version is defined }} \
          --kubeconfig /etc/kubernetes/admin.conf \
          --namespace kube-system \
          --values {{ kubernetes_config_directory }}/cilium.yaml \
          2>&1 | tee /etc/kubernetes/output/cilium-installed
      creates: "{{ kubernetes_output_directory }}/cilium-installed"
      executable: /bin/bash

  - name: Wait for Cilium to be ready
    delay: 1
    register: cilium_pods
    # ~120 seconds
    retries: 12
    until: cilium_pods.rc == 0
    when: install_cilium
    ansible.builtin.command: kubectl --kubeconfig /etc/kubernetes/admin.conf --namespace kube-system wait --for=condition=Ready pod -l k8s-app=cilium --timeout=10s

  - name: Give it another few seconds
    when: install_cilium
    ansible.builtin.pause:
      seconds: 10

  rescue:
  - name: Cilium variable contents
    when: cilium is defined
    ansible.builtin.debug:
      var: cilium

  - name: Cilium failed
    ansible.builtin.fail:
      msg: Cilium failed to install
