- name: Enable device ownership from security context
  register: device_ownership_replace
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: "device_ownership_from_security_context = .*"
    replace: "device_ownership_from_security_context = true"

- name: Restart containerd service
  register: device_ownership_restart
  when: device_ownership_replace.changed
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Wait for containerd to restart
  when: device_ownership_restart.changed
  ansible.builtin.pause:
    seconds: 10
