- name: Configure nodes for Calico on RHEL family
  when: ansible_facts.os_family == "RedHat"
  block:
  - name: Check if firewalld is installed
    register: firewalld_package
    ansible.builtin.package_facts:
      manager: auto

  - name: Disable firewalld
    when: "'firewalld' in ansible_facts.packages"
    ansible.builtin.service:
      enabled: false
      name: firewalld
      state: stopped

  - name: Configure NetworkManager to ignore Calico interfaces
    register: calico_nm_config
    ansible.builtin.copy:
      content: |
        [keyfile]
        unmanaged-devices=interface-name:cali*;interface-name:tunl*;interface-name:vxlan.calico;interface-name:vxlan-v6.calico;interface-name:wireguard.cali;interface-name:wg-v6.cali
      dest: /etc/NetworkManager/conf.d/calico.conf
      group: root
      mode: "0644"
      owner: root

  - name: Restart NetworkManager when Calico config changes
    when:
    - calico_nm_config is changed
    ansible.builtin.service:
      name: NetworkManager
      state: restarted
