- name: Install Sealed Secret
  delegate_to: "{{ first_kube_control_plane }}"
  run_once: true
  block:
  - name: Check for Sealed Secrets
    register: sealed_secrets_installed_cmd
    ansible.builtin.shell:
      cmd: |
        kubectl get pods -n kube-system --kubeconfig /etc/kubernetes/admin.conf | grep sealed-secrets > /dev/null && echo -n "Installed" || echo "Not installed"
        echo "Installed"

  - name: Set install_sealed_secrets fact
    ansible.builtin.set_fact:
      install_sealed_secrets: "{{ sealed_secrets_installed_cmd.stdout_lines[0] == 'Not installed' }}"

  - name: Install Sealed Secrets
    when: install_sealed_secrets
    ansible.builtin.shell:
      cmd: |
        set -eo pipefail
        helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
        helm install sealed-secrets \
          --kubeconfig /etc/kubernetes/admin.conf \
          -n kube-system \
          --set-string fullnameOverride=sealed-secrets-controller \
          sealed-secrets/sealed-secrets
      executable: /bin/bash

  rescue:
  - name: Sealed Secrets failed to install
    ansible.builtin.fail:
      msg: Sealed Secrets failed to install
